---
- hosts: all
  tasks:
    - name: Confirm that 200 OK response is returned
      uri:
        url: "https://tts.service-now.com//api/tcdps/incident_rest_demo/getinc/b61f5f4c1bac31908fd7404be54bcb38"
        method: GET
    - debug:
        var: results
